---
title: "cGAS"
author: "Rachel Washart"
date: "5/17/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(readxl)
library(dplyr)
expression <- read_excel("cGAS-STING-expression.xlsx")
copynumber <- read_excel("cGAS-STING-copy.xlsx")
mutation <- read_excel("cGAS-STING-mutation.xlsx")
info <- read_excel("cell-line-info.xlsx")
```


```{r cgas percent, eval = F}
expression %>%
  summarise(mean = mean(CGAS_express)) %>%
  summarise(mean / 10)
```


```{r dataset, include=FALSE}
cgas_mutation <- mutation %>%
  filter(CGAS == 1)

cGAS_data <- expression %>%
  filter(CGAS_express < 0.220941) %>%
  inner_join(copynumber) %>%
  inner_join(info) %>%
  anti_join(cgas_mutation) %>%
  select(lineage_1, CGAS_express, CGAS_copy, cell_line)
```

## Plots

```{r plot1}
cGAS_data %>%
  filter(lineage_1 == "Skin") %>%
ggplot(aes(x = CGAS_express, y = CGAS_copy)) +
  geom_point() +
  geom_text(aes(x = CGAS_express, y = CGAS_copy, label = cell_line), size = 3,
            hjust = -0.1)
```
